# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Headers, footers, page setup, and section properties.

Run from the offidized-py crate directory:
    cd crates/offidized-py && uv run python examples/docx/03_headers_footers_sections.py

python-docx can set headers/footers but the API is verbose (requires
accessing XML sections, creating paragraphs within them). offidized
exposes headers, footers, page size, orientation, and all margins as
direct method calls on the section object.
"""

from offidized import Document

doc = Document()

# ─── Page setup ─────────────────────────────────────────────────────────
section = doc.section()

# Letter size in twips (1 inch = 1440 twips)
section.set_page_size_twips(12240, 15840)  # 8.5" x 11"
section.set_page_orientation("portrait")

# Margins
section.set_margin_top_twips(1440)  # 1 inch
section.set_margin_bottom_twips(1440)
section.set_margin_left_twips(1440)
section.set_margin_right_twips(1440)
section.set_margin_header_twips(720)  # 0.5 inch
section.set_margin_footer_twips(720)

# ─── Headers and footers ───────────────────────────────────────────────
section.set_header_text("ACME Corp — Confidential")
section.set_footer_text("Page 1 of 1 | Generated by offidized")

# First-page header/footer (different from default)
section.set_first_page_header_text("ACME Corp — Annual Report 2026")
section.set_first_page_footer_text("Draft — Not for Distribution")

# Even-page header/footer
section.set_even_page_header_text("ACME Corp — Confidential (Even)")
section.set_even_page_footer_text("Even Page Footer | offidized")

# ─── Document content ──────────────────────────────────────────────────
doc.add_heading("Document with Full Page Setup", 1)

doc.add_paragraph(
    "This document demonstrates offidized's page setup capabilities. "
    "The section properties control page size, orientation, margins, "
    "and headers/footers — all set with simple method calls."
)

doc.add_heading("Page Properties Set", 2)
doc.add_bulleted_paragraph('Page size: 8.5" x 11" (Letter)')
doc.add_bulleted_paragraph("Orientation: Portrait")
doc.add_bulleted_paragraph("Margins: 1 inch all around")
doc.add_bulleted_paragraph("Header/footer margin: 0.5 inch")

doc.add_heading("Header/Footer Variants", 2)
doc.add_bulleted_paragraph('Default header: "ACME Corp — Confidential"')
doc.add_bulleted_paragraph('First-page header: "ACME Corp — Annual Report 2026"')
doc.add_bulleted_paragraph("Even-page header: differs from odd pages")
doc.add_bulleted_paragraph("Each has a matching footer")

doc.add_heading("Why This Matters", 2)
doc.add_paragraph(
    "python-docx requires creating paragraph objects inside header/footer "
    "sections, then manually adding runs with formatting. offidized reduces "
    "this to a single set_header_text() call. For programmatic document "
    "generation (reports, invoices, contracts), this cuts boilerplate significantly."
)

# ─── Verify we can read back ───────────────────────────────────────────
print(f"Page width: {section.page_width_twips()} twips")
print(f"Page height: {section.page_height_twips()} twips")
print(f"Orientation: {section.page_orientation()}")
print(f"Header: {section.header_text()}")
print(f"Footer: {section.footer_text()}")
print(f"First-page header: {section.first_page_header_text()}")

doc.save("03_headers_footers_sections.docx")
print("Created 03_headers_footers_sections.docx")
