//! # offidized-schema
//!
//! Generated Rust types for OOXML schema elements.
//!
//! This crate is mostly auto-generated by `offidized-codegen` from the OOXML
//! XSD/JSON schema data. It provides typed structs for every XML element in
//! SpreadsheetML, WordprocessingML, and PresentationML.
//!
//! ## Roundtrip Preservation
//!
//! Every generated struct includes `unknown_children` and `unknown_attrs` fields.
//! During deserialization, any XML elements or attributes not recognized by the
//! struct are captured here. During serialization, they're written back in their
//! original position. This guarantees lossless roundtripping even for features
//! the high-level API doesn't yet support.

pub mod catalog;
mod generated;
pub mod raw;

#[cfg(feature = "xlsx")]
pub mod spreadsheetml;

#[cfg(feature = "docx")]
pub mod wordprocessingml;

#[cfg(feature = "pptx")]
pub mod presentationml;

pub mod shared;

pub use raw::RawXmlNode;
